services:
  - type: web
    name: floodcast-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 10000
      - key: DEBUG
        value: "False"
      - key: FLASK_ENV
        value: "production"
